#!/usr/bin/env python3
"""Generate FileDescriptorSet as C header for foxglove.CompressedImage schema."""
import sys
from google.protobuf import descriptor_pb2

fds = descriptor_pb2.FileDescriptorSet()

# --- google/protobuf/timestamp.proto ---
ts_file = fds.file.add()
ts_file.name = "google/protobuf/timestamp.proto"
ts_file.package = "google.protobuf"
ts_file.syntax = "proto3"
ts_msg = ts_file.message_type.add()
ts_msg.name = "Timestamp"
f1 = ts_msg.field.add()
f1.name = "seconds"
f1.number = 1
f1.type = 3  # TYPE_INT64
f2 = ts_msg.field.add()
f2.name = "nanos"
f2.number = 2
f2.type = 5  # TYPE_INT32

# --- foxglove/CompressedImage.proto ---
ci_file = fds.file.add()
ci_file.name = "foxglove/CompressedImage.proto"
ci_file.package = "foxglove"
ci_file.syntax = "proto3"
ci_file.dependency.append("google/protobuf/timestamp.proto")
ci_msg = ci_file.message_type.add()
ci_msg.name = "CompressedImage"
f = ci_msg.field.add()
f.name = "timestamp"
f.number = 1
f.type = 11  # TYPE_MESSAGE
f.type_name = ".google.protobuf.Timestamp"
f = ci_msg.field.add()
f.name = "frame_id"
f.number = 4
f.type = 9  # TYPE_STRING
f = ci_msg.field.add()
f.name = "data"
f.number = 2
f.type = 12  # TYPE_BYTES
f = ci_msg.field.add()
f.name = "format"
f.number = 3
f.type = 9  # TYPE_STRING

data = fds.SerializeToString()

out_path = sys.argv[1] if len(sys.argv) > 1 else \
    "/home/orange/pi-workspace/DartControl/config/autogenerated_proto/CompressedImageSchema_generated.h"

with open(out_path, "w") as fout:
    fout.write("// Auto-generated FileDescriptorSet for foxglove.CompressedImage\n")
    fout.write("#pragma once\n")
    fout.write("#include <cstddef>\n")
    fout.write("namespace foxglove {\n")
    fout.write("inline const unsigned char CompressedImageSchema_data[] = {\n")
    for i, b in enumerate(data):
        fout.write(" 0x{:02x},".format(b))
        if (i + 1) % 16 == 0:
            fout.write("\n")
    fout.write("\n};\n")
    fout.write("inline constexpr std::size_t CompressedImageSchema_size = {};\n".format(len(data)))
    fout.write("}  // namespace foxglove\n")

print("Generated: {} ({} bytes)".format(out_path, len(data)))
