# 规定目标系统 与 CPU架构
SET(CMAKE_SYSTEM_NAME Linux) 
SET(CMAKE_SYSTEM_PROCESSOR aarch64)  

# 规定交叉编译器
SET(CMAKE_C_COMPILER   aarch64-linux-gnu-gcc) 
SET(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++) 

# 规定头文件和库文件查找地址，将树莓派开发环境从本地隔离
SET(CMAKE_SYSROOT $ENV{HOME}/rpi-sysroot) 
SET(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT}) 

# 安全锁：只找树莓派的库和头文件 ， 不找电脑本机的库和头文件
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)