namespace foxglove;

table CarData
{
    acc_frd_x_mg : float;
    acc_frd_y_mg : float;
    acc_frd_z_mg : float;
    gyro_frd_x_dps : float;
    gyro_frd_y_dps : float;
    gyro_frd_z_dps : float;
    gyro_raw_frd_x_dps : float;
    gyro_raw_frd_y_dps : float;
    gyro_raw_frd_z_dps : float;
    euler_roll : float;
    euler_yaw : float;
    euler_pitch : float;
    roll_raw : float;
    pitch_raw : float;
    yaw_raw : float;
    roll_diff : float;
    pitch_diff : float;
    yaw_diff : float;
    quat_roll : float;
    quat_pitch : float;
    quat_yaw : float;
    IMU_index : int;
    IMU_fps : int;
    m_cpu_usage : int;
    m_state : int;
}
root_type CarData;