namespace foxglove;

table CarData
{
    state : int;
    imu_fps : int;

    acc_raw_frd_x_mg : float;
    acc_raw_frd_y_mg : float;
    acc_raw_frd_z_mg : float;

    acc_filtered_frd_x_mg : float;
    acc_filtered_frd_y_mg : float;
    acc_filtered_frd_z_mg : float;

    gyro_raw_frd_x_dps : float;
    gyro_raw_frd_y_dps : float;
    gyro_raw_frd_z_dps : float;

    gyro_filtered_frd_x_dps : float;
    gyro_filtered_frd_y_dps : float;
    gyro_filtered_frd_z_dps : float;

    attitude_roll_deg : float;
    attitude_yaw_deg : float;
    attitude_pitch_deg : float;

    attitude_unfiltered_roll_deg : float;
    attitude_unfiltered_yaw_deg : float;
    attitude_unfiltered_pitch_deg : float;

    attitude_direct_integral_roll_deg : float;
    attitude_direct_integral_yaw_deg : float;
    attitude_direct_integral_pitch_deg : float;
}

root_type CarData;
