// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CARDATA_FOXGLOVE_H_
#define FLATBUFFERS_GENERATED_CARDATA_FOXGLOVE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

// For access to the binary schema that produced this file.
#include "CarData_bfbs_generated.h"

namespace foxglove {

struct CarData;
struct CarDataBuilder;

struct CarData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CarDataBuilder Builder;
  typedef foxglove::CarDataBinarySchema BinarySchema;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STATE = 4,
    VT_IMU_FPS = 6,
    VT_ACC_RAW_FRD_X_MG = 8,
    VT_ACC_RAW_FRD_Y_MG = 10,
    VT_ACC_RAW_FRD_Z_MG = 12,
    VT_ACC_FILTERED_FRD_X_MG = 14,
    VT_ACC_FILTERED_FRD_Y_MG = 16,
    VT_ACC_FILTERED_FRD_Z_MG = 18,
    VT_GYRO_RAW_FRD_X_DPS = 20,
    VT_GYRO_RAW_FRD_Y_DPS = 22,
    VT_GYRO_RAW_FRD_Z_DPS = 24,
    VT_GYRO_FILTERED_FRD_X_DPS = 26,
    VT_GYRO_FILTERED_FRD_Y_DPS = 28,
    VT_GYRO_FILTERED_FRD_Z_DPS = 30,
    VT_ATTITUDE_ROLL_DEG = 32,
    VT_ATTITUDE_YAW_DEG = 34,
    VT_ATTITUDE_PITCH_DEG = 36,
    VT_ATTITUDE_UNFILTERED_ROLL_DEG = 38,
    VT_ATTITUDE_UNFILTERED_YAW_DEG = 40,
    VT_ATTITUDE_UNFILTERED_PITCH_DEG = 42,
    VT_ATTITUDE_DIRECT_INTEGRAL_ROLL_DEG = 44,
    VT_ATTITUDE_DIRECT_INTEGRAL_YAW_DEG = 46,
    VT_ATTITUDE_DIRECT_INTEGRAL_PITCH_DEG = 48
  };
  int32_t state() const {
    return GetField<int32_t>(VT_STATE, 0);
  }
  int32_t imu_fps() const {
    return GetField<int32_t>(VT_IMU_FPS, 0);
  }
  float acc_raw_frd_x_mg() const {
    return GetField<float>(VT_ACC_RAW_FRD_X_MG, 0.0f);
  }
  float acc_raw_frd_y_mg() const {
    return GetField<float>(VT_ACC_RAW_FRD_Y_MG, 0.0f);
  }
  float acc_raw_frd_z_mg() const {
    return GetField<float>(VT_ACC_RAW_FRD_Z_MG, 0.0f);
  }
  float acc_filtered_frd_x_mg() const {
    return GetField<float>(VT_ACC_FILTERED_FRD_X_MG, 0.0f);
  }
  float acc_filtered_frd_y_mg() const {
    return GetField<float>(VT_ACC_FILTERED_FRD_Y_MG, 0.0f);
  }
  float acc_filtered_frd_z_mg() const {
    return GetField<float>(VT_ACC_FILTERED_FRD_Z_MG, 0.0f);
  }
  float gyro_raw_frd_x_dps() const {
    return GetField<float>(VT_GYRO_RAW_FRD_X_DPS, 0.0f);
  }
  float gyro_raw_frd_y_dps() const {
    return GetField<float>(VT_GYRO_RAW_FRD_Y_DPS, 0.0f);
  }
  float gyro_raw_frd_z_dps() const {
    return GetField<float>(VT_GYRO_RAW_FRD_Z_DPS, 0.0f);
  }
  float gyro_filtered_frd_x_dps() const {
    return GetField<float>(VT_GYRO_FILTERED_FRD_X_DPS, 0.0f);
  }
  float gyro_filtered_frd_y_dps() const {
    return GetField<float>(VT_GYRO_FILTERED_FRD_Y_DPS, 0.0f);
  }
  float gyro_filtered_frd_z_dps() const {
    return GetField<float>(VT_GYRO_FILTERED_FRD_Z_DPS, 0.0f);
  }
  float attitude_roll_deg() const {
    return GetField<float>(VT_ATTITUDE_ROLL_DEG, 0.0f);
  }
  float attitude_yaw_deg() const {
    return GetField<float>(VT_ATTITUDE_YAW_DEG, 0.0f);
  }
  float attitude_pitch_deg() const {
    return GetField<float>(VT_ATTITUDE_PITCH_DEG, 0.0f);
  }
  float attitude_unfiltered_roll_deg() const {
    return GetField<float>(VT_ATTITUDE_UNFILTERED_ROLL_DEG, 0.0f);
  }
  float attitude_unfiltered_yaw_deg() const {
    return GetField<float>(VT_ATTITUDE_UNFILTERED_YAW_DEG, 0.0f);
  }
  float attitude_unfiltered_pitch_deg() const {
    return GetField<float>(VT_ATTITUDE_UNFILTERED_PITCH_DEG, 0.0f);
  }
  float attitude_direct_integral_roll_deg() const {
    return GetField<float>(VT_ATTITUDE_DIRECT_INTEGRAL_ROLL_DEG, 0.0f);
  }
  float attitude_direct_integral_yaw_deg() const {
    return GetField<float>(VT_ATTITUDE_DIRECT_INTEGRAL_YAW_DEG, 0.0f);
  }
  float attitude_direct_integral_pitch_deg() const {
    return GetField<float>(VT_ATTITUDE_DIRECT_INTEGRAL_PITCH_DEG, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_STATE, 4) &&
           VerifyField<int32_t>(verifier, VT_IMU_FPS, 4) &&
           VerifyField<float>(verifier, VT_ACC_RAW_FRD_X_MG, 4) &&
           VerifyField<float>(verifier, VT_ACC_RAW_FRD_Y_MG, 4) &&
           VerifyField<float>(verifier, VT_ACC_RAW_FRD_Z_MG, 4) &&
           VerifyField<float>(verifier, VT_ACC_FILTERED_FRD_X_MG, 4) &&
           VerifyField<float>(verifier, VT_ACC_FILTERED_FRD_Y_MG, 4) &&
           VerifyField<float>(verifier, VT_ACC_FILTERED_FRD_Z_MG, 4) &&
           VerifyField<float>(verifier, VT_GYRO_RAW_FRD_X_DPS, 4) &&
           VerifyField<float>(verifier, VT_GYRO_RAW_FRD_Y_DPS, 4) &&
           VerifyField<float>(verifier, VT_GYRO_RAW_FRD_Z_DPS, 4) &&
           VerifyField<float>(verifier, VT_GYRO_FILTERED_FRD_X_DPS, 4) &&
           VerifyField<float>(verifier, VT_GYRO_FILTERED_FRD_Y_DPS, 4) &&
           VerifyField<float>(verifier, VT_GYRO_FILTERED_FRD_Z_DPS, 4) &&
           VerifyField<float>(verifier, VT_ATTITUDE_ROLL_DEG, 4) &&
           VerifyField<float>(verifier, VT_ATTITUDE_YAW_DEG, 4) &&
           VerifyField<float>(verifier, VT_ATTITUDE_PITCH_DEG, 4) &&
           VerifyField<float>(verifier, VT_ATTITUDE_UNFILTERED_ROLL_DEG, 4) &&
           VerifyField<float>(verifier, VT_ATTITUDE_UNFILTERED_YAW_DEG, 4) &&
           VerifyField<float>(verifier, VT_ATTITUDE_UNFILTERED_PITCH_DEG, 4) &&
           VerifyField<float>(verifier, VT_ATTITUDE_DIRECT_INTEGRAL_ROLL_DEG, 4) &&
           VerifyField<float>(verifier, VT_ATTITUDE_DIRECT_INTEGRAL_YAW_DEG, 4) &&
           VerifyField<float>(verifier, VT_ATTITUDE_DIRECT_INTEGRAL_PITCH_DEG, 4) &&
           verifier.EndTable();
  }
};

struct CarDataBuilder {
  typedef CarData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_state(int32_t state) {
    fbb_.AddElement<int32_t>(CarData::VT_STATE, state, 0);
  }
  void add_imu_fps(int32_t imu_fps) {
    fbb_.AddElement<int32_t>(CarData::VT_IMU_FPS, imu_fps, 0);
  }
  void add_acc_raw_frd_x_mg(float acc_raw_frd_x_mg) {
    fbb_.AddElement<float>(CarData::VT_ACC_RAW_FRD_X_MG, acc_raw_frd_x_mg, 0.0f);
  }
  void add_acc_raw_frd_y_mg(float acc_raw_frd_y_mg) {
    fbb_.AddElement<float>(CarData::VT_ACC_RAW_FRD_Y_MG, acc_raw_frd_y_mg, 0.0f);
  }
  void add_acc_raw_frd_z_mg(float acc_raw_frd_z_mg) {
    fbb_.AddElement<float>(CarData::VT_ACC_RAW_FRD_Z_MG, acc_raw_frd_z_mg, 0.0f);
  }
  void add_acc_filtered_frd_x_mg(float acc_filtered_frd_x_mg) {
    fbb_.AddElement<float>(CarData::VT_ACC_FILTERED_FRD_X_MG, acc_filtered_frd_x_mg, 0.0f);
  }
  void add_acc_filtered_frd_y_mg(float acc_filtered_frd_y_mg) {
    fbb_.AddElement<float>(CarData::VT_ACC_FILTERED_FRD_Y_MG, acc_filtered_frd_y_mg, 0.0f);
  }
  void add_acc_filtered_frd_z_mg(float acc_filtered_frd_z_mg) {
    fbb_.AddElement<float>(CarData::VT_ACC_FILTERED_FRD_Z_MG, acc_filtered_frd_z_mg, 0.0f);
  }
  void add_gyro_raw_frd_x_dps(float gyro_raw_frd_x_dps) {
    fbb_.AddElement<float>(CarData::VT_GYRO_RAW_FRD_X_DPS, gyro_raw_frd_x_dps, 0.0f);
  }
  void add_gyro_raw_frd_y_dps(float gyro_raw_frd_y_dps) {
    fbb_.AddElement<float>(CarData::VT_GYRO_RAW_FRD_Y_DPS, gyro_raw_frd_y_dps, 0.0f);
  }
  void add_gyro_raw_frd_z_dps(float gyro_raw_frd_z_dps) {
    fbb_.AddElement<float>(CarData::VT_GYRO_RAW_FRD_Z_DPS, gyro_raw_frd_z_dps, 0.0f);
  }
  void add_gyro_filtered_frd_x_dps(float gyro_filtered_frd_x_dps) {
    fbb_.AddElement<float>(CarData::VT_GYRO_FILTERED_FRD_X_DPS, gyro_filtered_frd_x_dps, 0.0f);
  }
  void add_gyro_filtered_frd_y_dps(float gyro_filtered_frd_y_dps) {
    fbb_.AddElement<float>(CarData::VT_GYRO_FILTERED_FRD_Y_DPS, gyro_filtered_frd_y_dps, 0.0f);
  }
  void add_gyro_filtered_frd_z_dps(float gyro_filtered_frd_z_dps) {
    fbb_.AddElement<float>(CarData::VT_GYRO_FILTERED_FRD_Z_DPS, gyro_filtered_frd_z_dps, 0.0f);
  }
  void add_attitude_roll_deg(float attitude_roll_deg) {
    fbb_.AddElement<float>(CarData::VT_ATTITUDE_ROLL_DEG, attitude_roll_deg, 0.0f);
  }
  void add_attitude_yaw_deg(float attitude_yaw_deg) {
    fbb_.AddElement<float>(CarData::VT_ATTITUDE_YAW_DEG, attitude_yaw_deg, 0.0f);
  }
  void add_attitude_pitch_deg(float attitude_pitch_deg) {
    fbb_.AddElement<float>(CarData::VT_ATTITUDE_PITCH_DEG, attitude_pitch_deg, 0.0f);
  }
  void add_attitude_unfiltered_roll_deg(float attitude_unfiltered_roll_deg) {
    fbb_.AddElement<float>(CarData::VT_ATTITUDE_UNFILTERED_ROLL_DEG, attitude_unfiltered_roll_deg, 0.0f);
  }
  void add_attitude_unfiltered_yaw_deg(float attitude_unfiltered_yaw_deg) {
    fbb_.AddElement<float>(CarData::VT_ATTITUDE_UNFILTERED_YAW_DEG, attitude_unfiltered_yaw_deg, 0.0f);
  }
  void add_attitude_unfiltered_pitch_deg(float attitude_unfiltered_pitch_deg) {
    fbb_.AddElement<float>(CarData::VT_ATTITUDE_UNFILTERED_PITCH_DEG, attitude_unfiltered_pitch_deg, 0.0f);
  }
  void add_attitude_direct_integral_roll_deg(float attitude_direct_integral_roll_deg) {
    fbb_.AddElement<float>(CarData::VT_ATTITUDE_DIRECT_INTEGRAL_ROLL_DEG, attitude_direct_integral_roll_deg, 0.0f);
  }
  void add_attitude_direct_integral_yaw_deg(float attitude_direct_integral_yaw_deg) {
    fbb_.AddElement<float>(CarData::VT_ATTITUDE_DIRECT_INTEGRAL_YAW_DEG, attitude_direct_integral_yaw_deg, 0.0f);
  }
  void add_attitude_direct_integral_pitch_deg(float attitude_direct_integral_pitch_deg) {
    fbb_.AddElement<float>(CarData::VT_ATTITUDE_DIRECT_INTEGRAL_PITCH_DEG, attitude_direct_integral_pitch_deg, 0.0f);
  }
  explicit CarDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CarData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CarData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CarData> CreateCarData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t state = 0,
    int32_t imu_fps = 0,
    float acc_raw_frd_x_mg = 0.0f,
    float acc_raw_frd_y_mg = 0.0f,
    float acc_raw_frd_z_mg = 0.0f,
    float acc_filtered_frd_x_mg = 0.0f,
    float acc_filtered_frd_y_mg = 0.0f,
    float acc_filtered_frd_z_mg = 0.0f,
    float gyro_raw_frd_x_dps = 0.0f,
    float gyro_raw_frd_y_dps = 0.0f,
    float gyro_raw_frd_z_dps = 0.0f,
    float gyro_filtered_frd_x_dps = 0.0f,
    float gyro_filtered_frd_y_dps = 0.0f,
    float gyro_filtered_frd_z_dps = 0.0f,
    float attitude_roll_deg = 0.0f,
    float attitude_yaw_deg = 0.0f,
    float attitude_pitch_deg = 0.0f,
    float attitude_unfiltered_roll_deg = 0.0f,
    float attitude_unfiltered_yaw_deg = 0.0f,
    float attitude_unfiltered_pitch_deg = 0.0f,
    float attitude_direct_integral_roll_deg = 0.0f,
    float attitude_direct_integral_yaw_deg = 0.0f,
    float attitude_direct_integral_pitch_deg = 0.0f) {
  CarDataBuilder builder_(_fbb);
  builder_.add_attitude_direct_integral_pitch_deg(attitude_direct_integral_pitch_deg);
  builder_.add_attitude_direct_integral_yaw_deg(attitude_direct_integral_yaw_deg);
  builder_.add_attitude_direct_integral_roll_deg(attitude_direct_integral_roll_deg);
  builder_.add_attitude_unfiltered_pitch_deg(attitude_unfiltered_pitch_deg);
  builder_.add_attitude_unfiltered_yaw_deg(attitude_unfiltered_yaw_deg);
  builder_.add_attitude_unfiltered_roll_deg(attitude_unfiltered_roll_deg);
  builder_.add_attitude_pitch_deg(attitude_pitch_deg);
  builder_.add_attitude_yaw_deg(attitude_yaw_deg);
  builder_.add_attitude_roll_deg(attitude_roll_deg);
  builder_.add_gyro_filtered_frd_z_dps(gyro_filtered_frd_z_dps);
  builder_.add_gyro_filtered_frd_y_dps(gyro_filtered_frd_y_dps);
  builder_.add_gyro_filtered_frd_x_dps(gyro_filtered_frd_x_dps);
  builder_.add_gyro_raw_frd_z_dps(gyro_raw_frd_z_dps);
  builder_.add_gyro_raw_frd_y_dps(gyro_raw_frd_y_dps);
  builder_.add_gyro_raw_frd_x_dps(gyro_raw_frd_x_dps);
  builder_.add_acc_filtered_frd_z_mg(acc_filtered_frd_z_mg);
  builder_.add_acc_filtered_frd_y_mg(acc_filtered_frd_y_mg);
  builder_.add_acc_filtered_frd_x_mg(acc_filtered_frd_x_mg);
  builder_.add_acc_raw_frd_z_mg(acc_raw_frd_z_mg);
  builder_.add_acc_raw_frd_y_mg(acc_raw_frd_y_mg);
  builder_.add_acc_raw_frd_x_mg(acc_raw_frd_x_mg);
  builder_.add_imu_fps(imu_fps);
  builder_.add_state(state);
  return builder_.Finish();
}

inline const foxglove::CarData *GetCarData(const void *buf) {
  return ::flatbuffers::GetRoot<foxglove::CarData>(buf);
}

inline const foxglove::CarData *GetSizePrefixedCarData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<foxglove::CarData>(buf);
}

inline bool VerifyCarDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<foxglove::CarData>(nullptr);
}

inline bool VerifySizePrefixedCarDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<foxglove::CarData>(nullptr);
}

inline const char *CarDataExtension() {
  return "bfbs";
}

inline void FinishCarDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foxglove::CarData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedCarDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foxglove::CarData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace foxglove

#endif  // FLATBUFFERS_GENERATED_CARDATA_FOXGLOVE_H_
