// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CARDATA_FOXGLOVE_H_
#define FLATBUFFERS_GENERATED_CARDATA_FOXGLOVE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

// For access to the binary schema that produced this file.
#include "CarData_bfbs_generated.h"

namespace foxglove {

struct CarData;
struct CarDataBuilder;

struct CarData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CarDataBuilder Builder;
  typedef foxglove::CarDataBinarySchema BinarySchema;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACC_FRD_X_MG = 4,
    VT_ACC_FRD_Y_MG = 6,
    VT_ACC_FRD_Z_MG = 8,
    VT_GYRO_FRD_X_DPS = 10,
    VT_GYRO_FRD_Y_DPS = 12,
    VT_GYRO_FRD_Z_DPS = 14,
    VT_ROLL = 16,
    VT_YAW = 18,
    VT_PITCH = 20,
    VT_INDEX = 22,
    VT_CPU_USAGE = 24,
    VT_FPS = 26,
    VT_TARGET_PIXEL_X = 28,
    VT_TARGET_PIXEL_Y = 30,
    VT_TARGET_STATUS = 32,
    VT_FRAME_DT_MS = 34
  };
  float acc_frd_x_mg() const {
    return GetField<float>(VT_ACC_FRD_X_MG, 0.0f);
  }
  float acc_frd_y_mg() const {
    return GetField<float>(VT_ACC_FRD_Y_MG, 0.0f);
  }
  float acc_frd_z_mg() const {
    return GetField<float>(VT_ACC_FRD_Z_MG, 0.0f);
  }
  float gyro_frd_x_dps() const {
    return GetField<float>(VT_GYRO_FRD_X_DPS, 0.0f);
  }
  float gyro_frd_y_dps() const {
    return GetField<float>(VT_GYRO_FRD_Y_DPS, 0.0f);
  }
  float gyro_frd_z_dps() const {
    return GetField<float>(VT_GYRO_FRD_Z_DPS, 0.0f);
  }
  float roll() const {
    return GetField<float>(VT_ROLL, 0.0f);
  }
  float yaw() const {
    return GetField<float>(VT_YAW, 0.0f);
  }
  float pitch() const {
    return GetField<float>(VT_PITCH, 0.0f);
  }
  float index() const {
    return GetField<float>(VT_INDEX, 0.0f);
  }
  double cpu_usage() const {
    return GetField<double>(VT_CPU_USAGE, 0.0);
  }
  double fps() const {
    return GetField<double>(VT_FPS, 0.0);
  }
  int32_t target_pixel_x() const {
    return GetField<int32_t>(VT_TARGET_PIXEL_X, 0);
  }
  int32_t target_pixel_y() const {
    return GetField<int32_t>(VT_TARGET_PIXEL_Y, 0);
  }
  int32_t target_status() const {
    return GetField<int32_t>(VT_TARGET_STATUS, 0);
  }
  int32_t frame_dt_ms() const {
    return GetField<int32_t>(VT_FRAME_DT_MS, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_ACC_FRD_X_MG, 4) &&
           VerifyField<float>(verifier, VT_ACC_FRD_Y_MG, 4) &&
           VerifyField<float>(verifier, VT_ACC_FRD_Z_MG, 4) &&
           VerifyField<float>(verifier, VT_GYRO_FRD_X_DPS, 4) &&
           VerifyField<float>(verifier, VT_GYRO_FRD_Y_DPS, 4) &&
           VerifyField<float>(verifier, VT_GYRO_FRD_Z_DPS, 4) &&
           VerifyField<float>(verifier, VT_ROLL, 4) &&
           VerifyField<float>(verifier, VT_YAW, 4) &&
           VerifyField<float>(verifier, VT_PITCH, 4) &&
           VerifyField<float>(verifier, VT_INDEX, 4) &&
           VerifyField<double>(verifier, VT_CPU_USAGE, 8) &&
           VerifyField<double>(verifier, VT_FPS, 8) &&
           VerifyField<int32_t>(verifier, VT_TARGET_PIXEL_X, 4) &&
           VerifyField<int32_t>(verifier, VT_TARGET_PIXEL_Y, 4) &&
           VerifyField<int32_t>(verifier, VT_TARGET_STATUS, 4) &&
           VerifyField<int32_t>(verifier, VT_FRAME_DT_MS, 4) &&
           verifier.EndTable();
  }
};

struct CarDataBuilder {
  typedef CarData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_acc_frd_x_mg(float acc_frd_x_mg) {
    fbb_.AddElement<float>(CarData::VT_ACC_FRD_X_MG, acc_frd_x_mg, 0.0f);
  }
  void add_acc_frd_y_mg(float acc_frd_y_mg) {
    fbb_.AddElement<float>(CarData::VT_ACC_FRD_Y_MG, acc_frd_y_mg, 0.0f);
  }
  void add_acc_frd_z_mg(float acc_frd_z_mg) {
    fbb_.AddElement<float>(CarData::VT_ACC_FRD_Z_MG, acc_frd_z_mg, 0.0f);
  }
  void add_gyro_frd_x_dps(float gyro_frd_x_dps) {
    fbb_.AddElement<float>(CarData::VT_GYRO_FRD_X_DPS, gyro_frd_x_dps, 0.0f);
  }
  void add_gyro_frd_y_dps(float gyro_frd_y_dps) {
    fbb_.AddElement<float>(CarData::VT_GYRO_FRD_Y_DPS, gyro_frd_y_dps, 0.0f);
  }
  void add_gyro_frd_z_dps(float gyro_frd_z_dps) {
    fbb_.AddElement<float>(CarData::VT_GYRO_FRD_Z_DPS, gyro_frd_z_dps, 0.0f);
  }
  void add_roll(float roll) {
    fbb_.AddElement<float>(CarData::VT_ROLL, roll, 0.0f);
  }
  void add_yaw(float yaw) {
    fbb_.AddElement<float>(CarData::VT_YAW, yaw, 0.0f);
  }
  void add_pitch(float pitch) {
    fbb_.AddElement<float>(CarData::VT_PITCH, pitch, 0.0f);
  }
  void add_index(float index) {
    fbb_.AddElement<float>(CarData::VT_INDEX, index, 0.0f);
  }
  void add_cpu_usage(double cpu_usage) {
    fbb_.AddElement<double>(CarData::VT_CPU_USAGE, cpu_usage, 0.0);
  }
  void add_fps(double fps) {
    fbb_.AddElement<double>(CarData::VT_FPS, fps, 0.0);
  }
  void add_target_pixel_x(int32_t target_pixel_x) {
    fbb_.AddElement<int32_t>(CarData::VT_TARGET_PIXEL_X, target_pixel_x, 0);
  }
  void add_target_pixel_y(int32_t target_pixel_y) {
    fbb_.AddElement<int32_t>(CarData::VT_TARGET_PIXEL_Y, target_pixel_y, 0);
  }
  void add_target_status(int32_t target_status) {
    fbb_.AddElement<int32_t>(CarData::VT_TARGET_STATUS, target_status, 0);
  }
  void add_frame_dt_ms(int32_t frame_dt_ms) {
    fbb_.AddElement<int32_t>(CarData::VT_FRAME_DT_MS, frame_dt_ms, 0);
  }
  explicit CarDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CarData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CarData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CarData> CreateCarData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float acc_frd_x_mg = 0.0f,
    float acc_frd_y_mg = 0.0f,
    float acc_frd_z_mg = 0.0f,
    float gyro_frd_x_dps = 0.0f,
    float gyro_frd_y_dps = 0.0f,
    float gyro_frd_z_dps = 0.0f,
    float roll = 0.0f,
    float yaw = 0.0f,
    float pitch = 0.0f,
    float index = 0.0f,
    double cpu_usage = 0.0,
    double fps = 0.0,
    int32_t target_pixel_x = 0,
    int32_t target_pixel_y = 0,
    int32_t target_status = 0,
    int32_t frame_dt_ms = 0) {
  CarDataBuilder builder_(_fbb);
  builder_.add_fps(fps);
  builder_.add_cpu_usage(cpu_usage);
  builder_.add_frame_dt_ms(frame_dt_ms);
  builder_.add_target_status(target_status);
  builder_.add_target_pixel_y(target_pixel_y);
  builder_.add_target_pixel_x(target_pixel_x);
  builder_.add_index(index);
  builder_.add_pitch(pitch);
  builder_.add_yaw(yaw);
  builder_.add_roll(roll);
  builder_.add_gyro_frd_z_dps(gyro_frd_z_dps);
  builder_.add_gyro_frd_y_dps(gyro_frd_y_dps);
  builder_.add_gyro_frd_x_dps(gyro_frd_x_dps);
  builder_.add_acc_frd_z_mg(acc_frd_z_mg);
  builder_.add_acc_frd_y_mg(acc_frd_y_mg);
  builder_.add_acc_frd_x_mg(acc_frd_x_mg);
  return builder_.Finish();
}

inline const foxglove::CarData *GetCarData(const void *buf) {
  return ::flatbuffers::GetRoot<foxglove::CarData>(buf);
}

inline const foxglove::CarData *GetSizePrefixedCarData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<foxglove::CarData>(buf);
}

inline bool VerifyCarDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<foxglove::CarData>(nullptr);
}

inline bool VerifySizePrefixedCarDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<foxglove::CarData>(nullptr);
}

inline void FinishCarDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foxglove::CarData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedCarDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foxglove::CarData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace foxglove

#endif  // FLATBUFFERS_GENERATED_CARDATA_FOXGLOVE_H_
