// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CARDATA_FOXGLOVE_H_
#define FLATBUFFERS_GENERATED_CARDATA_FOXGLOVE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

// For access to the binary schema that produced this file.
#include "CarData_bfbs_generated.h"

namespace foxglove {

struct CarData;
struct CarDataBuilder;

struct CarData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CarDataBuilder Builder;
  typedef foxglove::CarDataBinarySchema BinarySchema;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACCFRDXMG = 4,
    VT_ACCFRDYMG = 6,
    VT_ACCFRDZMG = 8,
    VT_GYROFRDXDPS = 10,
    VT_GYROFRDYDPS = 12,
    VT_GYROFRDZDPS = 14,
    VT_ROLL = 16,
    VT_YAW = 18,
    VT_PITCH = 20,
    VT_IMUINDEX = 22,
    VT_IMUFPS = 24,
    VT_CPUUSAGE = 26,
    VT_STATE = 28
  };
  float accFrdXMg() const {
    return GetField<float>(VT_ACCFRDXMG, 0.0f);
  }
  float accFrdYMg() const {
    return GetField<float>(VT_ACCFRDYMG, 0.0f);
  }
  float accFrdZMg() const {
    return GetField<float>(VT_ACCFRDZMG, 0.0f);
  }
  float gyroFrdXDps() const {
    return GetField<float>(VT_GYROFRDXDPS, 0.0f);
  }
  float gyroFrdYDps() const {
    return GetField<float>(VT_GYROFRDYDPS, 0.0f);
  }
  float gyroFrdZDps() const {
    return GetField<float>(VT_GYROFRDZDPS, 0.0f);
  }
  float roll() const {
    return GetField<float>(VT_ROLL, 0.0f);
  }
  float yaw() const {
    return GetField<float>(VT_YAW, 0.0f);
  }
  float pitch() const {
    return GetField<float>(VT_PITCH, 0.0f);
  }
  int32_t iMUIndex() const {
    return GetField<int32_t>(VT_IMUINDEX, 0);
  }
  int32_t iMUFps() const {
    return GetField<int32_t>(VT_IMUFPS, 0);
  }
  int32_t cpuUsage() const {
    return GetField<int32_t>(VT_CPUUSAGE, 0);
  }
  int32_t state() const {
    return GetField<int32_t>(VT_STATE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_ACCFRDXMG, 4) &&
           VerifyField<float>(verifier, VT_ACCFRDYMG, 4) &&
           VerifyField<float>(verifier, VT_ACCFRDZMG, 4) &&
           VerifyField<float>(verifier, VT_GYROFRDXDPS, 4) &&
           VerifyField<float>(verifier, VT_GYROFRDYDPS, 4) &&
           VerifyField<float>(verifier, VT_GYROFRDZDPS, 4) &&
           VerifyField<float>(verifier, VT_ROLL, 4) &&
           VerifyField<float>(verifier, VT_YAW, 4) &&
           VerifyField<float>(verifier, VT_PITCH, 4) &&
           VerifyField<int32_t>(verifier, VT_IMUINDEX, 4) &&
           VerifyField<int32_t>(verifier, VT_IMUFPS, 4) &&
           VerifyField<int32_t>(verifier, VT_CPUUSAGE, 4) &&
           VerifyField<int32_t>(verifier, VT_STATE, 4) &&
           verifier.EndTable();
  }
};

struct CarDataBuilder {
  typedef CarData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_accFrdXMg(float accFrdXMg) {
    fbb_.AddElement<float>(CarData::VT_ACCFRDXMG, accFrdXMg, 0.0f);
  }
  void add_accFrdYMg(float accFrdYMg) {
    fbb_.AddElement<float>(CarData::VT_ACCFRDYMG, accFrdYMg, 0.0f);
  }
  void add_accFrdZMg(float accFrdZMg) {
    fbb_.AddElement<float>(CarData::VT_ACCFRDZMG, accFrdZMg, 0.0f);
  }
  void add_gyroFrdXDps(float gyroFrdXDps) {
    fbb_.AddElement<float>(CarData::VT_GYROFRDXDPS, gyroFrdXDps, 0.0f);
  }
  void add_gyroFrdYDps(float gyroFrdYDps) {
    fbb_.AddElement<float>(CarData::VT_GYROFRDYDPS, gyroFrdYDps, 0.0f);
  }
  void add_gyroFrdZDps(float gyroFrdZDps) {
    fbb_.AddElement<float>(CarData::VT_GYROFRDZDPS, gyroFrdZDps, 0.0f);
  }
  void add_roll(float roll) {
    fbb_.AddElement<float>(CarData::VT_ROLL, roll, 0.0f);
  }
  void add_yaw(float yaw) {
    fbb_.AddElement<float>(CarData::VT_YAW, yaw, 0.0f);
  }
  void add_pitch(float pitch) {
    fbb_.AddElement<float>(CarData::VT_PITCH, pitch, 0.0f);
  }
  void add_iMUIndex(int32_t iMUIndex) {
    fbb_.AddElement<int32_t>(CarData::VT_IMUINDEX, iMUIndex, 0);
  }
  void add_iMUFps(int32_t iMUFps) {
    fbb_.AddElement<int32_t>(CarData::VT_IMUFPS, iMUFps, 0);
  }
  void add_cpuUsage(int32_t cpuUsage) {
    fbb_.AddElement<int32_t>(CarData::VT_CPUUSAGE, cpuUsage, 0);
  }
  void add_state(int32_t state) {
    fbb_.AddElement<int32_t>(CarData::VT_STATE, state, 0);
  }
  explicit CarDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CarData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CarData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CarData> CreateCarData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float accFrdXMg = 0.0f,
    float accFrdYMg = 0.0f,
    float accFrdZMg = 0.0f,
    float gyroFrdXDps = 0.0f,
    float gyroFrdYDps = 0.0f,
    float gyroFrdZDps = 0.0f,
    float roll = 0.0f,
    float yaw = 0.0f,
    float pitch = 0.0f,
    int32_t iMUIndex = 0,
    int32_t iMUFps = 0,
    int32_t cpuUsage = 0,
    int32_t state = 0) {
  CarDataBuilder builder_(_fbb);
  builder_.add_state(state);
  builder_.add_cpuUsage(cpuUsage);
  builder_.add_iMUFps(iMUFps);
  builder_.add_iMUIndex(iMUIndex);
  builder_.add_pitch(pitch);
  builder_.add_yaw(yaw);
  builder_.add_roll(roll);
  builder_.add_gyroFrdZDps(gyroFrdZDps);
  builder_.add_gyroFrdYDps(gyroFrdYDps);
  builder_.add_gyroFrdXDps(gyroFrdXDps);
  builder_.add_accFrdZMg(accFrdZMg);
  builder_.add_accFrdYMg(accFrdYMg);
  builder_.add_accFrdXMg(accFrdXMg);
  return builder_.Finish();
}

inline const foxglove::CarData *GetCarData(const void *buf) {
  return ::flatbuffers::GetRoot<foxglove::CarData>(buf);
}

inline const foxglove::CarData *GetSizePrefixedCarData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<foxglove::CarData>(buf);
}

inline bool VerifyCarDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<foxglove::CarData>(nullptr);
}

inline bool VerifySizePrefixedCarDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<foxglove::CarData>(nullptr);
}

inline void FinishCarDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foxglove::CarData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedCarDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foxglove::CarData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace foxglove

#endif  // FLATBUFFERS_GENERATED_CARDATA_FOXGLOVE_H_
