// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_VISIONDATA_FOXGLOVE_H_
#define FLATBUFFERS_GENERATED_VISIONDATA_FOXGLOVE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

// For access to the binary schema that produced this file.
#include "VisionData_bfbs_generated.h"

namespace foxglove {

struct Vision;
struct VisionBuilder;

struct Vision FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VisionBuilder Builder;
  typedef foxglove::VisionBinarySchema BinarySchema;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_PIXEL_X = 4,
    VT_TARGET_PIXEL_Y = 6,
    VT_TARGET_STATUS = 8,
    VT_FRAME_DT_MS = 10,
    VT_VIDEO_FPS = 12
  };
  int32_t target_pixel_x() const {
    return GetField<int32_t>(VT_TARGET_PIXEL_X, 0);
  }
  int32_t target_pixel_y() const {
    return GetField<int32_t>(VT_TARGET_PIXEL_Y, 0);
  }
  int32_t target_status() const {
    return GetField<int32_t>(VT_TARGET_STATUS, 0);
  }
  int32_t frame_dt_ms() const {
    return GetField<int32_t>(VT_FRAME_DT_MS, 0);
  }
  int32_t video_fps() const {
    return GetField<int32_t>(VT_VIDEO_FPS, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TARGET_PIXEL_X, 4) &&
           VerifyField<int32_t>(verifier, VT_TARGET_PIXEL_Y, 4) &&
           VerifyField<int32_t>(verifier, VT_TARGET_STATUS, 4) &&
           VerifyField<int32_t>(verifier, VT_FRAME_DT_MS, 4) &&
           VerifyField<int32_t>(verifier, VT_VIDEO_FPS, 4) &&
           verifier.EndTable();
  }
};

struct VisionBuilder {
  typedef Vision Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_pixel_x(int32_t target_pixel_x) {
    fbb_.AddElement<int32_t>(Vision::VT_TARGET_PIXEL_X, target_pixel_x, 0);
  }
  void add_target_pixel_y(int32_t target_pixel_y) {
    fbb_.AddElement<int32_t>(Vision::VT_TARGET_PIXEL_Y, target_pixel_y, 0);
  }
  void add_target_status(int32_t target_status) {
    fbb_.AddElement<int32_t>(Vision::VT_TARGET_STATUS, target_status, 0);
  }
  void add_frame_dt_ms(int32_t frame_dt_ms) {
    fbb_.AddElement<int32_t>(Vision::VT_FRAME_DT_MS, frame_dt_ms, 0);
  }
  void add_video_fps(int32_t video_fps) {
    fbb_.AddElement<int32_t>(Vision::VT_VIDEO_FPS, video_fps, 0);
  }
  explicit VisionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vision> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vision>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vision> CreateVision(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t target_pixel_x = 0,
    int32_t target_pixel_y = 0,
    int32_t target_status = 0,
    int32_t frame_dt_ms = 0,
    int32_t video_fps = 0) {
  VisionBuilder builder_(_fbb);
  builder_.add_video_fps(video_fps);
  builder_.add_frame_dt_ms(frame_dt_ms);
  builder_.add_target_status(target_status);
  builder_.add_target_pixel_y(target_pixel_y);
  builder_.add_target_pixel_x(target_pixel_x);
  return builder_.Finish();
}

inline const foxglove::Vision *GetVision(const void *buf) {
  return ::flatbuffers::GetRoot<foxglove::Vision>(buf);
}

inline const foxglove::Vision *GetSizePrefixedVision(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<foxglove::Vision>(buf);
}

inline bool VerifyVisionBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<foxglove::Vision>(nullptr);
}

inline bool VerifySizePrefixedVisionBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<foxglove::Vision>(nullptr);
}

inline void FinishVisionBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foxglove::Vision> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedVisionBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foxglove::Vision> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace foxglove

#endif  // FLATBUFFERS_GENERATED_VISIONDATA_FOXGLOVE_H_
