#define MCAP_IMPLEMENTATION
#include "mcap/writer.hpp"
#include "capture.hpp"
#include "data_type.hpp"
#include "protobuf_helpers.hpp"
#include "../../config/autogenerated_flatbuffers/CarData_generated.h"
#include "../../config/autogenerated_flatbuffers/CarData_bfbs_generated.h"
#include "../../config/autogenerated_flatbuffers/VisionData_generated.h"
#include "../../config/autogenerated_flatbuffers/VisionData_bfbs_generated.h"
#include "../../config/autogenerated_proto/CompressedImageSchema_generated.h"

#include <iostream>
#include <fstream>
#include <filesystem>
#include <chrono>
#include <cstddef>
#include <ctime>
#include <stdexcept>
#include <opencv2/imgcodecs.hpp>
Capturer::Capturer()
{
    std::string bag_name_time = Capturer::get_local_time_now();
    m_mcap_path = "../bag/"+bag_name_time+ ".mcap" ;
    
}

Capturer::~Capturer()
{
    finish();  // 确保后台线程停止后再析构
}

bool Capturer::init()
{
    Capturer::try_to_create_target_file(m_mcap_path);
    auto status = m_mcap_writer.open(m_mcap_path,mcap::McapWriterOptions("flatbuffer"));
    if (!status.ok())
    {
        std::cerr << "[ERROR]<"<<m_mcap_path<<"> Failed to open MCAP file for writing: "  << status.message << std::endl;
        return false;
    }   
    m_CarData_schema_data = std::string(
        reinterpret_cast<const char*>(foxglove::CarDataBinarySchema::data()),
        foxglove::CarDataBinarySchema::size()
    );

    m_CarData_schema = std::make_unique<mcap::Schema>(m_CarData_schema_name,"flatbuffer",m_CarData_schema_data);
    m_mcap_writer.addSchema(*m_CarData_schema.get());

    m_CarData_channel = std::make_unique<mcap::Channel>(m_topic_name,"flatbuffer",m_CarData_schema.get()->id);
    m_mcap_writer.addChannel(*m_CarData_channel.get());

    // ── 注册视频 channel (protobuf 编码) ──
    m_video_schema_data = std::string(
        reinterpret_cast<const char*>(foxglove::CompressedImageSchema_data),
        foxglove::CompressedImageSchema_size
    );
    m_video_schema = std::make_unique<mcap::Schema>(
        m_video_schema_name, "protobuf", m_video_schema_data);
    m_mcap_writer.addSchema(*m_video_schema.get());

    m_video_channel = std::make_unique<mcap::Channel>(
        m_video_topic_name, "protobuf", m_video_schema.get()->id);
    m_mcap_writer.addChannel(*m_video_channel.get());

    // ── 注册视觉检测 channel (flatbuffer 编码) ──
    m_vision_schema_data = std::string(
        reinterpret_cast<const char*>(foxglove::VisionBinarySchema::data()),
        foxglove::VisionBinarySchema::size()
    );
    m_vision_schema = std::make_unique<mcap::Schema>(
        m_vision_schema_name, "flatbuffer", m_vision_schema_data);
    m_mcap_writer.addSchema(*m_vision_schema.get());

    m_vision_channel = std::make_unique<mcap::Channel>(
        m_vision_topic_name, "flatbuffer", m_vision_schema.get()->id);
    m_mcap_writer.addChannel(*m_vision_channel.get());

    // ── 启动后台视频写入线程 ──
    m_writer_running.store(true);
    m_writer_thread = std::thread(&Capturer::writer_thread_loop, this);

    m_opened = true;
    return true;
}

bool Capturer::update_car_data(CarData& car_data)
{
    m_builder.Clear();
    auto foxglove_car_data = foxglove::CreateCarData(
        this -> m_builder,
        car_data.acc_frd_x_mg,
        car_data.acc_frd_y_mg,
        car_data.acc_frd_z_mg,
        car_data.gyro_frd_x_dps,
        car_data.gyro_frd_y_dps,
        car_data.gyro_frd_z_dps,
        car_data.roll,
        car_data.yaw,
        car_data.pitch,
        car_data.IMU_index,
        car_data.IMU_fps,
        car_data.m_cpu_usage,
        car_data.m_state
    );
    m_builder.Finish(foxglove_car_data);

    auto data_pointer = m_builder.GetBufferPointer();
    auto data_size = m_builder.GetSize();

    mcap::Message message;
    auto now = std::chrono::system_clock::now();
    auto ns  = std::chrono::duration_cast<std::chrono::nanoseconds>(
                  now.time_since_epoch()
              ).count();
    message.channelId = m_CarData_channel->id;
    message.sequence = m_sequence++;
    message.logTime = ns;
    message.publishTime = ns;
    message.data = reinterpret_cast<std::byte*>(data_pointer);
    message.dataSize = data_size;

    {
        std::lock_guard<std::mutex> lock(m_writer_mutex);
        if (!m_mcap_writer.write(message).ok())
        {
            std::cerr << "[ERROR] mcap write failed!" << std::endl;
            return false;
        }
    }
    return true;
}

bool Capturer::write_video_frame(const cv::Mat& frame, int jpeg_quality)
{
    if (!m_opened || frame.empty())
        return false;

    // 1. 深拷贝原始帧（轻量 memcpy ~300KB，不做任何编码）
    cv::Mat cloned = frame.clone();

    // 2. 时间戳
    auto now = std::chrono::system_clock::now();
    auto ns  = std::chrono::duration_cast<std::chrono::nanoseconds>(
                  now.time_since_epoch()
              ).count();

    // 3. 构造帧并入队（非阻塞，后台线程负责编码+序列化+磁盘写入）
    EncodedFrame ef;
    ef.raw_frame    = std::move(cloned);
    ef.jpeg_quality = jpeg_quality;
    ef.channel_id   = m_video_channel->id;
    ef.sequence     = m_video_sequence++;
    ef.log_time     = ns;
    ef.publish_time = ns;

    {
        std::lock_guard<std::mutex> lock(m_queue_mutex);
        // 队列满则丢弃最旧帧（背压策略）
        if (m_write_queue.size() >= kMaxQueueSize)
        {
            m_write_queue.pop_front();
        }
        m_write_queue.push_back(std::move(ef));
    }
    m_queue_cv.notify_one();
    return true;
}

bool Capturer::write_vision_data(int target_pixel_x, int target_pixel_y,
                                 int target_status, int frame_dt_ms, int video_fps)
{
    if (!m_opened) return false;

    m_vision_builder.Clear();
    auto vision = foxglove::CreateVision(
        m_vision_builder,
        target_pixel_x,
        target_pixel_y,
        target_status,
        frame_dt_ms,
        video_fps
    );
    m_vision_builder.Finish(vision);

    auto now = std::chrono::system_clock::now();
    auto ns  = std::chrono::duration_cast<std::chrono::nanoseconds>(
                  now.time_since_epoch()
              ).count();

    mcap::Message msg;
    msg.channelId   = m_vision_channel->id;
    msg.sequence    = m_vision_sequence++;
    msg.logTime     = ns;
    msg.publishTime = ns;
    msg.data        = reinterpret_cast<std::byte*>(m_vision_builder.GetBufferPointer());
    msg.dataSize    = m_vision_builder.GetSize();

    std::lock_guard<std::mutex> lock(m_writer_mutex);
    auto status = m_mcap_writer.write(msg);
    if (!status.ok())
    {
        std::cerr << "[ERROR] mcap vision data write failed: " << status.message << std::endl;
        return false;
    }
    return true;
}

std::string Capturer::get_local_time_now()
{
    time_t now_time;
    time(&now_time);
    tm p{};
    localtime_r(&now_time, &p);
    std::string now_time_string = std::to_string(p.tm_year + 1900) + "_" +
                               std::to_string(p.tm_mon + 1) + "_" +
                               std::to_string(p.tm_mday) + "_" +
                               std::to_string(p.tm_hour) + "_" +
                               std::to_string(p.tm_min) + "_" +
                               std::to_string(p.tm_sec);
    return now_time_string;
}

void Capturer::try_to_create_target_file(std::string_view path)
{
    std::filesystem::path file(path);  
    if (!std::filesystem::exists(file)) 
    {
        std::cout << "["<< file << "] does not exit, try to create" << std::endl;
        try {
            std::filesystem::create_directories(file.parent_path());
            std::ofstream outfile(file);
            outfile.close();
        } catch (std::exception &e) {
            std::cout << "create [" << file << "] failed: " << e.what() << std::endl;
        }
    }
}
std::string Capturer::get_file_Contents(std::string_view path)
{
    // NOTE: This function is currently not called anywhere.
    std::ifstream infile;
    infile.open(path.data(), std::ios::binary | std::ios::in);

    if (!infile) {
        throw std::runtime_error("Could not open file " + std::string(path));
    }

    infile.seekg(0, std::ios::end);
    std::streamsize length = infile.tellg();
    infile.seekg(0, std::ios::beg);
    std::string result(length, '\0');
    infile.read(result.data(), length);
    infile.close();
    return result;
}
void Capturer::finish() {
    // 1. 通知后台线程停止并等待其排空队列
    if (m_writer_running.load())
    {
        m_writer_running.store(false);
        m_queue_cv.notify_one();
        if (m_writer_thread.joinable())
        {
            m_writer_thread.join();
        }
    }
    // 2. 关闭 MCAP writer
    if (m_opened)
    {
        this->m_mcap_writer.close();
        m_opened = false;
    }
}

void Capturer::writer_thread_loop()
{
    while (m_writer_running.load())
    {
        EncodedFrame ef;
        {
            std::unique_lock<std::mutex> lock(m_queue_mutex);
            m_queue_cv.wait(lock, [this] {
                return !m_write_queue.empty() || !m_writer_running.load();
            });

            if (!m_writer_running.load() && m_write_queue.empty())
                break;

            if (!m_write_queue.empty())
            {
                ef = std::move(m_write_queue.front());
                m_write_queue.pop_front();
            }
        } // 释放队列锁，让 producer 可以继续入队

        // ── JPEG 编码（仅后台线程使用 m_jpeg_buf，无线程竞争）──
        m_jpeg_buf.clear();
        std::vector<int> params = {cv::IMWRITE_JPEG_QUALITY, ef.jpeg_quality};
        if (!cv::imencode(".jpg", ef.raw_frame, m_jpeg_buf, params))
        {
            std::cerr << "[ERROR] JPEG encode failed in writer thread!" << std::endl;
            continue;
        }

        // ── protobuf 序列化 ──
        int64_t seconds = static_cast<int64_t>(ef.log_time / 1'000'000'000ULL);
        int32_t nanos   = static_cast<int32_t>(ef.log_time % 1'000'000'000ULL);
        m_pb_buf = foxglove::serialize_compressed_image(
            seconds, nanos, "camera", m_jpeg_buf.data(), m_jpeg_buf.size(), "jpeg");

        // ── 构造 mcap::Message 并写入磁盘 ──
        mcap::Message msg;
        msg.channelId   = ef.channel_id;
        msg.sequence    = ef.sequence;
        msg.logTime     = ef.log_time;
        msg.publishTime = ef.publish_time;
        msg.data        = reinterpret_cast<std::byte*>(m_pb_buf.data());
        msg.dataSize    = m_pb_buf.size();

        {
            std::lock_guard<std::mutex> lock(m_writer_mutex);
            auto status = m_mcap_writer.write(msg);
            if (!status.ok())
            {
                std::cerr << "[ERROR] mcap video write failed: "
                          << status.message << std::endl;
            }
        }
    }

    // 退出前排空队列中剩余的帧
    while (true)
    {
        EncodedFrame ef;
        {
            std::lock_guard<std::mutex> lock(m_queue_mutex);
            if (m_write_queue.empty())
                break;
            ef = std::move(m_write_queue.front());
            m_write_queue.pop_front();
        }

        m_jpeg_buf.clear();
        std::vector<int> params = {cv::IMWRITE_JPEG_QUALITY, ef.jpeg_quality};
        if (!cv::imencode(".jpg", ef.raw_frame, m_jpeg_buf, params))
        {
            std::cerr << "[ERROR] JPEG encode failed in drain!" << std::endl;
            continue;
        }

        int64_t seconds = static_cast<int64_t>(ef.log_time / 1'000'000'000ULL);
        int32_t nanos   = static_cast<int32_t>(ef.log_time % 1'000'000'000ULL);
        m_pb_buf = foxglove::serialize_compressed_image(
            seconds, nanos, "camera", m_jpeg_buf.data(), m_jpeg_buf.size(), "jpeg");

        mcap::Message msg;
        msg.channelId   = ef.channel_id;
        msg.sequence    = ef.sequence;
        msg.logTime     = ef.log_time;
        msg.publishTime = ef.publish_time;
        msg.data        = reinterpret_cast<std::byte*>(m_pb_buf.data());
        msg.dataSize    = m_pb_buf.size();

        {
            std::lock_guard<std::mutex> lock(m_writer_mutex);
            auto status = m_mcap_writer.write(msg);
            if (!status.ok())
            {
                std::cerr << "[ERROR] mcap video write failed (drain): "
                          << status.message << std::endl;
            }
        }
    }
}
