#define MCAP_IMPLEMENTATION
#include "mcap/writer.hpp"
#include "capture.hpp"
#include "data_type.hpp"
#include "../../config/autogenerated_flatbuffers/CarData_generated.h"
#include "../../config/autogenerated_flatbuffers/CarData_bfbs_generated.h"

#include <iostream>
#include <fstream>
#include <filesystem>
#include <chrono>
#include <cstddef>
#include <ctime>
#include <stdexcept>
Capture::Capture()
{
    std::string bag_name_time = Capture::get_local_time_now();
    m_mcap_path = "../bag/"+bag_name_time+ ".mcap" ;
    
}

Capture::~Capture()
{
    if (m_opened) {
        m_mcap_writer.close();
    }
}

bool Capture::init()
{
    Capture::try_to_create_target_file(m_mcap_path);
    auto status = m_mcap_writer.open(m_mcap_path,mcap::McapWriterOptions("flatbuffer"));
    if (!status.ok())
    {
        std::cerr << "[ERROR]<"<<m_mcap_path<<"> Failed to open MCAP file for writing: "  << status.message << std::endl;
        return false;
    }   
    m_CarData_schema_data = std::string(
        reinterpret_cast<const char*>(foxglove::CarDataBinarySchema::data()),
        foxglove::CarDataBinarySchema::size()
    );

    m_CarData_schema = std::make_unique<mcap::Schema>(m_CarData_schema_name,"flatbuffer",m_CarData_schema_data);
    m_mcap_writer.addSchema(*m_CarData_schema.get());

    m_CarData_channel = std::make_unique<mcap::Channel>(m_topic_name,"flatbuffer",m_CarData_schema.get()->id);
    m_mcap_writer.addChannel(*m_CarData_channel.get());

    m_opened = true;
    return true;
}

bool Capture::update(CarData& car_data)
{
    m_builder.Clear();
    auto foxglove_car_data = foxglove::CreateCarData(
        this -> m_builder,
        car_data.acc_frd_x_mg,
        car_data.acc_frd_y_mg,
        car_data.acc_frd_z_mg,
        car_data.gyro_frd_x_dps,
        car_data.gyro_frd_y_dps,
        car_data.gyro_frd_z_dps,
        car_data.roll,
        car_data.yaw,
        car_data.pitch,
        car_data.index,
        car_data.m_cpu_usage,
        car_data.m_fps,
        car_data.m_target_pixel_x,
        car_data.m_target_pixel_y,
        car_data.m_target_status,
        car_data.m_frame_dt_ms
    );
    m_builder.Finish(foxglove_car_data);

    auto data_pointer = m_builder.GetBufferPointer();
    auto data_size = m_builder.GetSize();

    mcap::Message message;
    auto now = std::chrono::system_clock::now();
    auto ns  = std::chrono::duration_cast<std::chrono::nanoseconds>(
                  now.time_since_epoch()
              ).count();
    message.channelId = m_CarData_channel->id;
    message.sequence = m_sequence++;
    message.logTime = ns;
    message.publishTime = ns;
    message.data = reinterpret_cast<std::byte*>(data_pointer);
    message.dataSize = data_size;

    if (!m_mcap_writer.write(message).ok())
    {
        std::cerr << "[ERROR] mcap write failed!" << std::endl;
        return false;
    }
    return true;
}

std::string Capture::get_local_time_now()
{
    time_t now_time;
    time(&now_time);
    tm p{};
    localtime_r(&now_time, &p);
    std::string now_time_string = std::to_string(p.tm_year + 1900) + "_" +
                               std::to_string(p.tm_mon + 1) + "_" +
                               std::to_string(p.tm_mday) + "_" +
                               std::to_string(p.tm_hour) + "_" +
                               std::to_string(p.tm_min) + "_" +
                               std::to_string(p.tm_sec);
    return now_time_string;
}

void Capture::try_to_create_target_file(std::string_view path)
{
    std::filesystem::path file(path);  
    if (!std::filesystem::exists(file)) 
    {
        std::cout << "["<< file << "] does not exit, try to create" << std::endl;
        try {
            std::filesystem::create_directories(file.parent_path());
            std::ofstream outfile(file);
            outfile.close();
        } catch (std::exception &e) {
            std::cout << "create [" << file << "] failed: " << e.what() << std::endl;
        }
    }
}
std::string Capture::get_file_Contents(std::string_view path)
{
    // NOTE: This function is currently not called anywhere.
    std::ifstream infile;
    infile.open(path.data(), std::ios::binary | std::ios::in);

    if (!infile) {
        throw std::runtime_error("Could not open file " + std::string(path));
    }

    infile.seekg(0, std::ios::end);
    std::streamsize length = infile.tellg();
    infile.seekg(0, std::ios::beg);
    std::string result(length, '\0');
    infile.read(result.data(), length);
    infile.close();
    return result;
}
void Capture::finish() {
    this->m_mcap_writer.close();
    m_opened = false;
}
