# automatically generated by the FlatBuffers compiler, do not modify

# namespace: foxglove

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CarData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CarData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCarData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CarData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CarData
    def AccFrdXMg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def AccFrdYMg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def AccFrdZMg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def GyroFrdXDps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def GyroFrdYDps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def GyroFrdZDps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def GyroRawFrdXDps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def GyroRawFrdYDps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def GyroRawFrdZDps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def Roll(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def Yaw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def Pitch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def RollRaw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def PitchRaw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def YawRaw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def RollDiff(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def PitchDiff(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def YawDiff(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def RollQ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def PitchQ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def YawQ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def ImuIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CarData
    def ImuFps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CarData
    def MCpuUsage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CarData
    def MState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def CarDataStart(builder):
    builder.StartObject(25)

def Start(builder):
    CarDataStart(builder)

def CarDataAddAccFrdXMg(builder, accFrdXMg):
    builder.PrependFloat32Slot(0, accFrdXMg, 0.0)

def AddAccFrdXMg(builder, accFrdXMg):
    CarDataAddAccFrdXMg(builder, accFrdXMg)

def CarDataAddAccFrdYMg(builder, accFrdYMg):
    builder.PrependFloat32Slot(1, accFrdYMg, 0.0)

def AddAccFrdYMg(builder, accFrdYMg):
    CarDataAddAccFrdYMg(builder, accFrdYMg)

def CarDataAddAccFrdZMg(builder, accFrdZMg):
    builder.PrependFloat32Slot(2, accFrdZMg, 0.0)

def AddAccFrdZMg(builder, accFrdZMg):
    CarDataAddAccFrdZMg(builder, accFrdZMg)

def CarDataAddGyroFrdXDps(builder, gyroFrdXDps):
    builder.PrependFloat32Slot(3, gyroFrdXDps, 0.0)

def AddGyroFrdXDps(builder, gyroFrdXDps):
    CarDataAddGyroFrdXDps(builder, gyroFrdXDps)

def CarDataAddGyroFrdYDps(builder, gyroFrdYDps):
    builder.PrependFloat32Slot(4, gyroFrdYDps, 0.0)

def AddGyroFrdYDps(builder, gyroFrdYDps):
    CarDataAddGyroFrdYDps(builder, gyroFrdYDps)

def CarDataAddGyroFrdZDps(builder, gyroFrdZDps):
    builder.PrependFloat32Slot(5, gyroFrdZDps, 0.0)

def AddGyroFrdZDps(builder, gyroFrdZDps):
    CarDataAddGyroFrdZDps(builder, gyroFrdZDps)

def CarDataAddGyroRawFrdXDps(builder, gyroRawFrdXDps):
    builder.PrependFloat32Slot(6, gyroRawFrdXDps, 0.0)

def AddGyroRawFrdXDps(builder, gyroRawFrdXDps):
    CarDataAddGyroRawFrdXDps(builder, gyroRawFrdXDps)

def CarDataAddGyroRawFrdYDps(builder, gyroRawFrdYDps):
    builder.PrependFloat32Slot(7, gyroRawFrdYDps, 0.0)

def AddGyroRawFrdYDps(builder, gyroRawFrdYDps):
    CarDataAddGyroRawFrdYDps(builder, gyroRawFrdYDps)

def CarDataAddGyroRawFrdZDps(builder, gyroRawFrdZDps):
    builder.PrependFloat32Slot(8, gyroRawFrdZDps, 0.0)

def AddGyroRawFrdZDps(builder, gyroRawFrdZDps):
    CarDataAddGyroRawFrdZDps(builder, gyroRawFrdZDps)

def CarDataAddRoll(builder, roll):
    builder.PrependFloat32Slot(9, roll, 0.0)

def AddRoll(builder, roll):
    CarDataAddRoll(builder, roll)

def CarDataAddYaw(builder, yaw):
    builder.PrependFloat32Slot(10, yaw, 0.0)

def AddYaw(builder, yaw):
    CarDataAddYaw(builder, yaw)

def CarDataAddPitch(builder, pitch):
    builder.PrependFloat32Slot(11, pitch, 0.0)

def AddPitch(builder, pitch):
    CarDataAddPitch(builder, pitch)

def CarDataAddRollRaw(builder, rollRaw):
    builder.PrependFloat32Slot(12, rollRaw, 0.0)

def AddRollRaw(builder, rollRaw):
    CarDataAddRollRaw(builder, rollRaw)

def CarDataAddPitchRaw(builder, pitchRaw):
    builder.PrependFloat32Slot(13, pitchRaw, 0.0)

def AddPitchRaw(builder, pitchRaw):
    CarDataAddPitchRaw(builder, pitchRaw)

def CarDataAddYawRaw(builder, yawRaw):
    builder.PrependFloat32Slot(14, yawRaw, 0.0)

def AddYawRaw(builder, yawRaw):
    CarDataAddYawRaw(builder, yawRaw)

def CarDataAddRollDiff(builder, rollDiff):
    builder.PrependFloat32Slot(15, rollDiff, 0.0)

def AddRollDiff(builder, rollDiff):
    CarDataAddRollDiff(builder, rollDiff)

def CarDataAddPitchDiff(builder, pitchDiff):
    builder.PrependFloat32Slot(16, pitchDiff, 0.0)

def AddPitchDiff(builder, pitchDiff):
    CarDataAddPitchDiff(builder, pitchDiff)

def CarDataAddYawDiff(builder, yawDiff):
    builder.PrependFloat32Slot(17, yawDiff, 0.0)

def AddYawDiff(builder, yawDiff):
    CarDataAddYawDiff(builder, yawDiff)

def CarDataAddRollQ(builder, rollQ):
    builder.PrependFloat32Slot(18, rollQ, 0.0)

def AddRollQ(builder, rollQ):
    CarDataAddRollQ(builder, rollQ)

def CarDataAddPitchQ(builder, pitchQ):
    builder.PrependFloat32Slot(19, pitchQ, 0.0)

def AddPitchQ(builder, pitchQ):
    CarDataAddPitchQ(builder, pitchQ)

def CarDataAddYawQ(builder, yawQ):
    builder.PrependFloat32Slot(20, yawQ, 0.0)

def AddYawQ(builder, yawQ):
    CarDataAddYawQ(builder, yawQ)

def CarDataAddImuIndex(builder, imuIndex):
    builder.PrependInt32Slot(21, imuIndex, 0)

def AddImuIndex(builder, imuIndex):
    CarDataAddImuIndex(builder, imuIndex)

def CarDataAddImuFps(builder, imuFps):
    builder.PrependInt32Slot(22, imuFps, 0)

def AddImuFps(builder, imuFps):
    CarDataAddImuFps(builder, imuFps)

def CarDataAddMCpuUsage(builder, mCpuUsage):
    builder.PrependInt32Slot(23, mCpuUsage, 0)

def AddMCpuUsage(builder, mCpuUsage):
    CarDataAddMCpuUsage(builder, mCpuUsage)

def CarDataAddMState(builder, mState):
    builder.PrependInt32Slot(24, mState, 0)

def AddMState(builder, mState):
    CarDataAddMState(builder, mState)

def CarDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return CarDataEnd(builder)
