# automatically generated by the FlatBuffers compiler, do not modify

# namespace: foxglove

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CarData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CarData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCarData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CarData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CarData
    def State(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CarData
    def ImuFps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CarData
    def AccRawFrdXMg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def AccRawFrdYMg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def AccRawFrdZMg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def AccFilteredFrdXMg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def AccFilteredFrdYMg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def AccFilteredFrdZMg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def GyroRawFrdXDps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def GyroRawFrdYDps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def GyroRawFrdZDps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def GyroFilteredFrdXDps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def GyroFilteredFrdYDps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def GyroFilteredFrdZDps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def AttitudeRollDeg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def AttitudeYawDeg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def AttitudePitchDeg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def AttitudeUnfilteredRollDeg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def AttitudeUnfilteredYawDeg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def AttitudeUnfilteredPitchDeg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def AttitudeDirectIntegralRollDeg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def AttitudeDirectIntegralYawDeg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CarData
    def AttitudeDirectIntegralPitchDeg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def CarDataStart(builder):
    builder.StartObject(23)

def Start(builder):
    CarDataStart(builder)

def CarDataAddState(builder, state):
    builder.PrependInt32Slot(0, state, 0)

def AddState(builder, state):
    CarDataAddState(builder, state)

def CarDataAddImuFps(builder, imuFps):
    builder.PrependInt32Slot(1, imuFps, 0)

def AddImuFps(builder, imuFps):
    CarDataAddImuFps(builder, imuFps)

def CarDataAddAccRawFrdXMg(builder, accRawFrdXMg):
    builder.PrependFloat32Slot(2, accRawFrdXMg, 0.0)

def AddAccRawFrdXMg(builder, accRawFrdXMg):
    CarDataAddAccRawFrdXMg(builder, accRawFrdXMg)

def CarDataAddAccRawFrdYMg(builder, accRawFrdYMg):
    builder.PrependFloat32Slot(3, accRawFrdYMg, 0.0)

def AddAccRawFrdYMg(builder, accRawFrdYMg):
    CarDataAddAccRawFrdYMg(builder, accRawFrdYMg)

def CarDataAddAccRawFrdZMg(builder, accRawFrdZMg):
    builder.PrependFloat32Slot(4, accRawFrdZMg, 0.0)

def AddAccRawFrdZMg(builder, accRawFrdZMg):
    CarDataAddAccRawFrdZMg(builder, accRawFrdZMg)

def CarDataAddAccFilteredFrdXMg(builder, accFilteredFrdXMg):
    builder.PrependFloat32Slot(5, accFilteredFrdXMg, 0.0)

def AddAccFilteredFrdXMg(builder, accFilteredFrdXMg):
    CarDataAddAccFilteredFrdXMg(builder, accFilteredFrdXMg)

def CarDataAddAccFilteredFrdYMg(builder, accFilteredFrdYMg):
    builder.PrependFloat32Slot(6, accFilteredFrdYMg, 0.0)

def AddAccFilteredFrdYMg(builder, accFilteredFrdYMg):
    CarDataAddAccFilteredFrdYMg(builder, accFilteredFrdYMg)

def CarDataAddAccFilteredFrdZMg(builder, accFilteredFrdZMg):
    builder.PrependFloat32Slot(7, accFilteredFrdZMg, 0.0)

def AddAccFilteredFrdZMg(builder, accFilteredFrdZMg):
    CarDataAddAccFilteredFrdZMg(builder, accFilteredFrdZMg)

def CarDataAddGyroRawFrdXDps(builder, gyroRawFrdXDps):
    builder.PrependFloat32Slot(8, gyroRawFrdXDps, 0.0)

def AddGyroRawFrdXDps(builder, gyroRawFrdXDps):
    CarDataAddGyroRawFrdXDps(builder, gyroRawFrdXDps)

def CarDataAddGyroRawFrdYDps(builder, gyroRawFrdYDps):
    builder.PrependFloat32Slot(9, gyroRawFrdYDps, 0.0)

def AddGyroRawFrdYDps(builder, gyroRawFrdYDps):
    CarDataAddGyroRawFrdYDps(builder, gyroRawFrdYDps)

def CarDataAddGyroRawFrdZDps(builder, gyroRawFrdZDps):
    builder.PrependFloat32Slot(10, gyroRawFrdZDps, 0.0)

def AddGyroRawFrdZDps(builder, gyroRawFrdZDps):
    CarDataAddGyroRawFrdZDps(builder, gyroRawFrdZDps)

def CarDataAddGyroFilteredFrdXDps(builder, gyroFilteredFrdXDps):
    builder.PrependFloat32Slot(11, gyroFilteredFrdXDps, 0.0)

def AddGyroFilteredFrdXDps(builder, gyroFilteredFrdXDps):
    CarDataAddGyroFilteredFrdXDps(builder, gyroFilteredFrdXDps)

def CarDataAddGyroFilteredFrdYDps(builder, gyroFilteredFrdYDps):
    builder.PrependFloat32Slot(12, gyroFilteredFrdYDps, 0.0)

def AddGyroFilteredFrdYDps(builder, gyroFilteredFrdYDps):
    CarDataAddGyroFilteredFrdYDps(builder, gyroFilteredFrdYDps)

def CarDataAddGyroFilteredFrdZDps(builder, gyroFilteredFrdZDps):
    builder.PrependFloat32Slot(13, gyroFilteredFrdZDps, 0.0)

def AddGyroFilteredFrdZDps(builder, gyroFilteredFrdZDps):
    CarDataAddGyroFilteredFrdZDps(builder, gyroFilteredFrdZDps)

def CarDataAddAttitudeRollDeg(builder, attitudeRollDeg):
    builder.PrependFloat32Slot(14, attitudeRollDeg, 0.0)

def AddAttitudeRollDeg(builder, attitudeRollDeg):
    CarDataAddAttitudeRollDeg(builder, attitudeRollDeg)

def CarDataAddAttitudeYawDeg(builder, attitudeYawDeg):
    builder.PrependFloat32Slot(15, attitudeYawDeg, 0.0)

def AddAttitudeYawDeg(builder, attitudeYawDeg):
    CarDataAddAttitudeYawDeg(builder, attitudeYawDeg)

def CarDataAddAttitudePitchDeg(builder, attitudePitchDeg):
    builder.PrependFloat32Slot(16, attitudePitchDeg, 0.0)

def AddAttitudePitchDeg(builder, attitudePitchDeg):
    CarDataAddAttitudePitchDeg(builder, attitudePitchDeg)

def CarDataAddAttitudeUnfilteredRollDeg(builder, attitudeUnfilteredRollDeg):
    builder.PrependFloat32Slot(17, attitudeUnfilteredRollDeg, 0.0)

def AddAttitudeUnfilteredRollDeg(builder, attitudeUnfilteredRollDeg):
    CarDataAddAttitudeUnfilteredRollDeg(builder, attitudeUnfilteredRollDeg)

def CarDataAddAttitudeUnfilteredYawDeg(builder, attitudeUnfilteredYawDeg):
    builder.PrependFloat32Slot(18, attitudeUnfilteredYawDeg, 0.0)

def AddAttitudeUnfilteredYawDeg(builder, attitudeUnfilteredYawDeg):
    CarDataAddAttitudeUnfilteredYawDeg(builder, attitudeUnfilteredYawDeg)

def CarDataAddAttitudeUnfilteredPitchDeg(builder, attitudeUnfilteredPitchDeg):
    builder.PrependFloat32Slot(19, attitudeUnfilteredPitchDeg, 0.0)

def AddAttitudeUnfilteredPitchDeg(builder, attitudeUnfilteredPitchDeg):
    CarDataAddAttitudeUnfilteredPitchDeg(builder, attitudeUnfilteredPitchDeg)

def CarDataAddAttitudeDirectIntegralRollDeg(builder, attitudeDirectIntegralRollDeg):
    builder.PrependFloat32Slot(20, attitudeDirectIntegralRollDeg, 0.0)

def AddAttitudeDirectIntegralRollDeg(builder, attitudeDirectIntegralRollDeg):
    CarDataAddAttitudeDirectIntegralRollDeg(builder, attitudeDirectIntegralRollDeg)

def CarDataAddAttitudeDirectIntegralYawDeg(builder, attitudeDirectIntegralYawDeg):
    builder.PrependFloat32Slot(21, attitudeDirectIntegralYawDeg, 0.0)

def AddAttitudeDirectIntegralYawDeg(builder, attitudeDirectIntegralYawDeg):
    CarDataAddAttitudeDirectIntegralYawDeg(builder, attitudeDirectIntegralYawDeg)

def CarDataAddAttitudeDirectIntegralPitchDeg(builder, attitudeDirectIntegralPitchDeg):
    builder.PrependFloat32Slot(22, attitudeDirectIntegralPitchDeg, 0.0)

def AddAttitudeDirectIntegralPitchDeg(builder, attitudeDirectIntegralPitchDeg):
    CarDataAddAttitudeDirectIntegralPitchDeg(builder, attitudeDirectIntegralPitchDeg)

def CarDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return CarDataEnd(builder)
