#!/usr/bin/env python3
"""
分析项目生成的 MCAP 中 Kalman 滤波前/后的三轴角速度：

1. 一阶差分样本方差 Var(x[k] - x[k-1])，单位 (deg/s)^2；
2. 使用归一化互相关估计滤波后数据相对滤波前数据的滞后时间。

无位置参数时，脚本会列出项目 bag 目录中的 MCAP 文件供用户选择；
也可以直接传入文件路径：

    python3 scripts/analyze_gyro_kf.py bag/2026_7_20_17_26_51.mcap

依赖：numpy、mcap、flatbuffers，以及项目生成的 CarData Python 模块。
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Iterable

import numpy as np
from mcap.reader import make_reader


PROJECT_ROOT = Path(__file__).resolve().parents[1]
BAG_DIR = PROJECT_ROOT / "bag"
FLATBUFFER_PY_DIR = PROJECT_ROOT / "config" / "autogenerated_flatbuffers"
sys.path.insert(0, str(FLATBUFFER_PY_DIR))

from foxglove.CarData import CarData  # noqa: E402


AXES = ("X", "Y", "Z")


def choose_mcap_file() -> Path:
    """按修改时间从新到旧列出 bag 目录中的 MCAP，并让用户编号选择。"""
    files = sorted(
        BAG_DIR.glob("*.mcap"),
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )
    if not files:
        raise FileNotFoundError(f"{BAG_DIR} 中没有找到 .mcap 文件")

    print(f"\n可用 MCAP 文件（目录：{BAG_DIR}）：")
    for index, path in enumerate(files, start=1):
        size_mib = path.stat().st_size / (1024 * 1024)
        print(f"  {index:>3}. {path.name:<42} {size_mib:>8.2f} MiB")

    while True:
        try:
            answer = input(f"\n请选择文件编号 [1-{len(files)}，默认 1]：").strip()
        except EOFError as exc:
            raise RuntimeError("当前终端无法读取文件编号，请通过命令行传入 MCAP 路径") from exc

        if answer == "":
            return files[0]
        try:
            selection = int(answer)
        except ValueError:
            print("输入无效：请输入整数编号。")
            continue
        if 1 <= selection <= len(files):
            return files[selection - 1]
        print(f"输入超出范围：请输入 1 到 {len(files)}。")


def resolve_mcap_path(argument: str | None) -> Path:
    if argument is None:
        return choose_mcap_file()

    path = Path(argument).expanduser()
    if not path.is_absolute():
        path = (PROJECT_ROOT / path).resolve()
    if not path.is_file():
        raise FileNotFoundError(f"MCAP 文件不存在：{path}")
    return path


def read_gyro_data(path: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """返回时间戳、KF 前角速度和 KF 后角速度，角速度单位均为 deg/s。"""
    timestamps_ns: list[int] = []
    raw_rates: list[tuple[float, float, float]] = []
    filtered_rates: list[tuple[float, float, float]] = []

    with path.open("rb") as stream:
        reader = make_reader(stream)
        for _, channel, message in reader.iter_messages(topics=["Dart"]):
            if channel.topic != "Dart":
                continue
            car_data = CarData.GetRootAsCarData(message.data, 0)
            timestamps_ns.append(message.log_time)
            raw_rates.append(
                (
                    car_data.GyroRawFrdXDps(),
                    car_data.GyroRawFrdYDps(),
                    car_data.GyroRawFrdZDps(),
                )
            )
            filtered_rates.append(
                (
                    car_data.GyroFrdXDps(),
                    car_data.GyroFrdYDps(),
                    car_data.GyroFrdZDps(),
                )
            )

    if len(timestamps_ns) < 3:
        raise RuntimeError(
            f"Dart 通道有效样本不足：读取到 {len(timestamps_ns)} 帧，至少需要 3 帧"
        )

    timestamps = np.asarray(timestamps_ns, dtype=np.float64) * 1.0e-9
    raw = np.asarray(raw_rates, dtype=np.float64)
    filtered = np.asarray(filtered_rates, dtype=np.float64)

    finite_mask = (
        np.isfinite(timestamps)
        & np.all(np.isfinite(raw), axis=1)
        & np.all(np.isfinite(filtered), axis=1)
    )
    if not np.all(finite_mask):
        removed = int(np.count_nonzero(~finite_mask))
        print(f"[WARNING] 丢弃 {removed} 帧包含 NaN/Inf 的数据。", file=sys.stderr)
        timestamps = timestamps[finite_mask]
        raw = raw[finite_mask]
        filtered = filtered[finite_mask]

    if len(timestamps) < 3:
        raise RuntimeError("移除无效数值后样本不足")
    return timestamps, raw, filtered


def first_difference_variance(values: np.ndarray) -> np.ndarray:
    """计算每轴一阶差分的样本方差（N-1 分母，即 ddof=1）。"""
    differences = np.diff(values, axis=0)
    if len(differences) < 2:
        raise RuntimeError("一阶差分样本不足，无法计算样本方差")
    return np.var(differences, axis=0, ddof=1)


def normalized_correlation_at_lag(
    raw: np.ndarray, filtered: np.ndarray, lag: int
) -> float:
    """
    计算指定整数 lag 的 Pearson 相关系数。

    lag > 0：比较 raw[k] 与 filtered[k + lag]，即滤波后信号滞后；
    lag < 0：表示滤波后信号领先。
    """
    if lag > 0:
        raw_segment = raw[:-lag]
        filtered_segment = filtered[lag:]
    elif lag < 0:
        raw_segment = raw[-lag:]
        filtered_segment = filtered[:lag]
    else:
        raw_segment = raw
        filtered_segment = filtered

    raw_centered = raw_segment - np.mean(raw_segment)
    filtered_centered = filtered_segment - np.mean(filtered_segment)
    denominator = np.linalg.norm(raw_centered) * np.linalg.norm(filtered_centered)
    if denominator <= np.finfo(np.float64).eps:
        return float("nan")
    return float(np.dot(raw_centered, filtered_centered) / denominator)


def estimate_lag(
    raw: np.ndarray,
    filtered: np.ndarray,
    sample_interval_s: float,
    max_lag_s: float,
) -> tuple[float, float, float]:
    """返回亚采样 lag、lag 秒数和峰值归一化互相关系数。"""
    max_lag_samples = max(1, int(round(max_lag_s / sample_interval_s)))
    # 保证每个候选 lag 仍有足够重叠数据，避免短记录的边界假峰。
    max_lag_samples = min(max_lag_samples, max(1, len(raw) // 4))

    lags = np.arange(-max_lag_samples, max_lag_samples + 1, dtype=np.int64)
    correlations = np.asarray(
        [normalized_correlation_at_lag(raw, filtered, int(lag)) for lag in lags]
    )
    if not np.any(np.isfinite(correlations)):
        raise RuntimeError("信号缺少变化，无法通过互相关估计滞后")

    peak_index = int(np.nanargmax(correlations))
    lag_samples = float(lags[peak_index])
    peak_correlation = float(correlations[peak_index])

    # 对互相关峰值及其左右两个点做抛物线插值，得到亚采样滞后估计。
    if 0 < peak_index < len(correlations) - 1:
        left = correlations[peak_index - 1]
        center = correlations[peak_index]
        right = correlations[peak_index + 1]
        denominator = left - 2.0 * center + right
        if np.isfinite(denominator) and abs(denominator) > 1.0e-15:
            offset = 0.5 * (left - right) / denominator
            if abs(offset) <= 1.0:
                lag_samples += float(offset)

    return lag_samples, lag_samples * sample_interval_s, peak_correlation


def print_vector(title: str, values: Iterable[float], unit: str) -> None:
    print(title)
    for axis, value in zip(AXES, values):
        print(f"  {axis}: {value:.9e} {unit}")


def analyze(path: Path, max_lag_ms: float) -> None:
    timestamps, raw, filtered = read_gyro_data(path)
    intervals = np.diff(timestamps)
    positive_intervals = intervals[intervals > 0.0]
    if len(positive_intervals) == 0:
        raise RuntimeError("MCAP 时间戳没有正向递增，无法换算滞后时间")

    median_dt = float(np.median(positive_intervals))
    mean_dt = float(np.mean(positive_intervals))
    duration = float(timestamps[-1] - timestamps[0])

    raw_diff_variance = first_difference_variance(raw)
    filtered_diff_variance = first_difference_variance(filtered)

    print("\n" + "=" * 78)
    print(f"MCAP：{path}")
    print(f"Dart 样本数：{len(timestamps)}")
    print(f"记录时长：{duration:.6f} s")
    print(f"平均采样频率：{1.0 / mean_dt:.3f} Hz")
    print(f"中位采样间隔：{median_dt * 1.0e3:.6f} ms")
    print("=" * 78)

    print("\n1. 一阶差分样本方差 Var(x[k] - x[k-1])")
    print_vector("\nKF 前原始角速度：", raw_diff_variance, "(deg/s)^2")
    print_vector("\nKF 后角速度：", filtered_diff_variance, "(deg/s)^2")

    reduction = np.divide(
        filtered_diff_variance,
        raw_diff_variance,
        out=np.full(3, np.nan),
        where=raw_diff_variance > 0.0,
    )
    print("\nKF 后 / KF 前一阶差分方差比：")
    for axis, ratio in zip(AXES, reduction):
        print(f"  {axis}: {ratio:.6f}（降低 {(1.0 - ratio) * 100.0:.3f}%）")

    print("\n2. 归一化互相关滞后估计")
    print(f"搜索范围：±{max_lag_ms:.3f} ms")
    print("符号约定：正值 = KF 后数据滞后 KF 前数据；负值 = KF 后数据领先。")
    for axis_index, axis in enumerate(AXES):
        try:
            lag_samples, lag_seconds, correlation = estimate_lag(
                raw[:, axis_index],
                filtered[:, axis_index],
                median_dt,
                max_lag_ms * 1.0e-3,
            )
            print(
                f"  {axis}: {lag_samples:+.4f} samples, "
                f"{lag_seconds * 1.0e3:+.6f} ms, "
                f"peak corr={correlation:.6f}"
            )
        except RuntimeError as exc:
            print(f"  {axis}: 无法估计（{exc}）")


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="分析 MCAP 中 KF 前后陀螺角速度的一阶差分方差和互相关滞后"
    )
    parser.add_argument(
        "mcap",
        nargs="?",
        help="MCAP 文件路径；省略时从项目 bag 目录交互选择",
    )
    parser.add_argument(
        "--max-lag-ms",
        type=float,
        default=100.0,
        help="互相关搜索的最大绝对滞后，单位 ms（默认：100）",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_arguments()
    if args.max_lag_ms <= 0.0:
        print("[ERROR] --max-lag-ms 必须大于 0", file=sys.stderr)
        return 2

    try:
        path = resolve_mcap_path(args.mcap)
        analyze(path, args.max_lag_ms)
    except (FileNotFoundError, RuntimeError, OSError, ValueError) as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
