import sys
import numpy as np
from mcap.reader import make_reader
import math

import sys
sys.path.append("./config/autogenerated_flatbuffers")
import foxglove.CarData as CarData

file_path = "bag/2026_7_14_21_46_10.mcap"
start_time_ns = None
gyro_x_raw_dps = []
gyro_y_raw_dps = []
gyro_z_raw_dps = []

print("Reading MCAP file...")
with open(file_path, "rb") as f:
    reader = make_reader(f)
    for schema, channel, message in reader.iter_messages(topics=["Dart"]):
        if start_time_ns is None:
            start_time_ns = message.log_time
        
        current_time_s = (message.log_time - start_time_ns) / 1e9
        
        if current_time_s >= 2.0 and current_time_s <= 4.0:
            car_data = CarData.CarData.GetRootAs(message.data, 0)
            gyro_x_raw_dps.append(car_data.GyroRawFrdXDps())
            gyro_y_raw_dps.append(car_data.GyroRawFrdYDps())
            gyro_z_raw_dps.append(car_data.GyroRawFrdZDps())
            
        if current_time_s > 4.0:
            break

print(f"Collected {len(gyro_x_raw_dps)} samples.")

if len(gyro_x_raw_dps) == 0:
    print("No data collected in the 2s~4s range.")
    sys.exit(0)

# Calculate variance (noise) in dps^2
var_x_dps2 = np.var(gyro_x_raw_dps)
var_y_dps2 = np.var(gyro_y_raw_dps)
var_z_dps2 = np.var(gyro_z_raw_dps)

# Convert to rad/s (1 degree = pi / 180 radians)
# Variance scales by the square of the constant: Var(cX) = c^2 Var(X)
dps_to_radps_factor = math.pi / 180.0
var_x_radps2 = var_x_dps2 * (dps_to_radps_factor ** 2)
var_y_radps2 = var_y_dps2 * (dps_to_radps_factor ** 2)
var_z_radps2 = var_z_dps2 * (dps_to_radps_factor ** 2)

print(f"Gyro Raw X noise variance: {var_x_radps2:.8e} rad^2/s^2")
print(f"Gyro Raw Y noise variance: {var_y_radps2:.8e} rad^2/s^2")
print(f"Gyro Raw Z noise variance: {var_z_radps2:.8e} rad^2/s^2")

