#!/usr/bin/env python3
"""
从 MCAP 文件中提取 CarData 消息的姿态数据，输出 CSV。
列：timestamp_s, roll, pitch, yaw, roll_q, pitch_q, yaw_q
"""

import sys
import os
import csv
from mcap.reader import make_reader
from pathlib import Path

# 添加 flatbuffers Python schema 路径
sys.path.insert(0, os.path.join(os.path.dirname(__file__),
                                "../config/autogenerated_flatbuffers"))
from foxglove.CarData import CarData


def extract_to_csv(mcap_path: str, csv_path: str):
    rows = []
    with open(mcap_path, "rb") as f:
        reader = make_reader(f)
        for schema, channel, message in reader.iter_messages():
            # 只处理 CarData 通道
            if channel.topic == "Dart":
                car = CarData.GetRootAsCarData(message.data, 0)
                ts_s = message.log_time / 1e9  # 纳秒 → 秒
                rows.append({
                    "timestamp_s": f"{ts_s:.6f}",
                    "roll":        f"{car.Roll():.4f}",
                    "pitch":       f"{car.Pitch():.4f}",
                    "yaw":         f"{car.Yaw():.4f}",
                    "roll_q":      f"{car.RollQ():.4f}",
                    "pitch_q":     f"{car.PitchQ():.4f}",
                    "yaw_q":       f"{car.YawQ():.4f}",
                })

    if not rows:
        print(f"[WARN] 未在 {mcap_path} 中找到 CarData 消息")
        return

    # 按时间排序（mcap 保证有序，但以防万一）
    rows.sort(key=lambda r: r["timestamp_s"])

    fieldnames = ["timestamp_s", "roll", "pitch", "yaw",
                  "roll_q", "pitch_q", "yaw_q"]
    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"[OK] 已提取 {len(rows)} 条数据")
    print(f"     源文件: {mcap_path}")
    print(f"     输出:   {csv_path}")


if __name__ == "__main__":
    # 默认路径
    bag_dir = Path(__file__).parent / ".." / "bag"
    mcap_files = sorted(bag_dir.glob("*.mcap"))

    if not mcap_files:
        print(f"[ERROR] bag 目录下没有 .mcap 文件: {bag_dir.resolve()}")
        sys.exit(1)

    # 取最新的 mcap 文件
    latest_mcap = str(mcap_files[-1])
    csv_output = latest_mcap.replace(".mcap", "_attitude.csv")

    if len(sys.argv) >= 2:
        latest_mcap = sys.argv[1]
    if len(sys.argv) >= 3:
        csv_output = sys.argv[2]

    extract_to_csv(latest_mcap, csv_output)
